### ISSUE TITLE
[documentation] autogenerate pretty formatting of docs

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus-py#9]
Goal: generate pretty docs using `uv`. please check: https://github.com/pawamoy/copier-uv
thanks to @kenibrewer recommendation!

- [x] add template
- [x] pass `make check-docs`, which checks if the documentation builds correctly

**Comment by mathysgrapotte** [comment]
pretty formatting of docs now autogenerates as of #21
